AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Layered Architecture Lambda with API Gateway

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13

Resources:
  LayeredArchitectureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: layered-architecture-example
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Events:
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.ap-northeast-2.amazonaws.com/Prod/"
